port: 8082
gin_mode: debug
log_level: info
use_mock: false

storage:
  ingest_dir: /opt/test

database:
  host: localhost
  port: 5432
  user: kong
  password: kongpassword
  dbname: kong
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  auto_migrate_enabled: true


redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

security:
  jwt_secret: "your-secret-key-here-must-be-32-bytes-long"
  jwt_expiration: 24h
  rate_limit_per_second: 100
  rate_limit_burst: 200
  kong_shared_secret: "kong-shared-secret-key-2024"      # Kong网关共享密钥
  service_secret_key: "kyc-service-secret-key-2024"      # 服务签名密钥
  encryption_key: "oM9P4o6b8ib+dO1oh571cyfuJPdGqi6W"

third_party:
  ocr_service:
#    url: "http://159.138.228.40:8080/vrlOCR"
    url: "http://159.138.228.40:8089/vrlOCR"
    api_key: "ocr-api-key"
    timeout: 300
    retry_count: 0
  
  face_service:
    url: "http://159.138.228.40:8070"
#    url: "http://159.138.228.40:8030"
    api_key: "face-api-key"
    timeout: 300
    retry_count: 0
  
  liveness_silent:
    url: "http://159.138.228.40:8060/vrlSilentLiveness"
    api_key: "liveness-api-key"
    timeout: 600
    retry_count: 0

  liveness_video:
    url: "http://159.138.228.40:8060/vrlMoveLiveness"
    api_key: "liveness-api-key"
    timeout: 600
    retry_count: 0

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
    namespace: "kyc"
    subsystem: "service"
    push_interval: "30s"
    histogram_buckets: [0.1, 0.5, 1, 2, 5, 10]
  alerting:
    # https://qiye.163.com/help/client-profile.html
#    email_smtp: smtp.qq.com
    email_smtp: imaphz.qiye.163.com
    email_from: ericlee@verilocale.com
    email_user: ericlee@verilocale.com
#    email_password: jqfsfgmymvwdbahi
    email_password: 8#7s%r#YDPUB@YkX
    email_port: 465
    email_tls: true
  
  tracing:
    enabled: true
    service_name: "kyc-service"
    service_version: "1.0.0"
    environment: "development"
    jaeger_endpoint: "http://localhost:14268/api/traces"
    sample_rate: 1.0
    log_spans: false